print("Digite o seu peso em Kilos: ")
peso = int(input())
print("Digite sua altura em metros ( Exemplo: 1.75 ): ")
altura = float(input())
imc = ( peso / ( altura * altura ))
print()
print("O seu IMC é aproximadamente de:", imc)
print()
input("Clique uma tecla para fechar o comando.")